version: "3.8"

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MONGODB_URI=mongodb://mongodb:27017/banking-ledger
      - JWT_SECRET=your-secret-key-change-in-production
    depends_on:
      - mongodb
    restart: unless-stopped
    networks:
      - app-network

  mongodb:
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
      # Run mongod as replica set for transaction support
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    command: ["--replSet", "rs0", "--bind_ip_all"]
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb-data:
